### ISSUE TITLE
Use buy price if no sell price

### ISSUE THREAD

**Issue by Maraumax** [arnapou/gw2tools#4]
In Golds, i have one item who is actually not in sell :

![image](https://user-images.githubusercontent.com/194488/32944395-bdd9b424-cb8f-11e7-88cc-2ede8c19e562.png)

Why not use buy if sell is null ?

**Comment by arnapou** [comment]
Please explain more. I don't see the problem.

**Comment by Maraumax** [comment]
I have on item on this characters who have buy offers but no sell offers.

I would be better if we take buy offer for item if there is no sell offer, no ?

**Comment by arnapou** [comment]
gw2tool.net is dead I close the issue.
